
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.cokeos.io
  resources:
  - units
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.cokeos.io
  resources:
  - units/finalizers
  verbs:
  - update
- apiGroups:
  - core.cokeos.io
  resources:
  - units/status
  verbs:
  - get
  - patch
  - update
