# permissions for end users to view tinies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tiny-viewer-role
rules:
- apiGroups:
  - core.cokeos.io
  resources:
  - tinies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.cokeos.io
  resources:
  - tinies/status
  verbs:
  - get
