# permissions for end users to edit tinies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tiny-editor-role
rules:
- apiGroups:
  - core.cokeos.io
  resources:
  - tinies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.cokeos.io
  resources:
  - tinies/status
  verbs:
  - get
