# permissions for end users to edit tunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunnel-editor-role
rules:
- apiGroups:
  - core.cokeos.io
  resources:
  - tunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.cokeos.io
  resources:
  - tunnels/status
  verbs:
  - get
